-   id: add-github-issue-prefix
    name: Add issue number as commit message prefix
    description: find github issue number and use prefix commit msg
    entry: add-github-issue-prefix
    language: python
    always_run: false
    stages: [prepare-commit-msg]
